---
title: DUOTEK.dev
email: dev@duotek.ru
description: |
  Копирование и распространение материалов приветствуется. Пожалуйста, сохраняйте авторство и указывайте ссылку на источник
baseurl: ''
url: ''
permalink: /:categories/:title.html
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
disqus:
  shortname: duotek
