---
title: Блог разработчиков Duotek
email: dev@duotek.ru
description: ''
baseurl: ''
url: https://duotek.github.io
permalink: /:categories/:title.html
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
disqus:
  shortname: duotek
